# Generated by Django 4.2.7 on 2023-12-07 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_accesscode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 3, 20, 56, 229572, tzinfo=datetime.timezone.utc)),
        ),
    ]
